---
- hosts: all
  sudo: yes
  gather_facts: no
  remote_user: user_name

  tasks:

  - name: install ssh key
    authorized_key: user=user_name 
                    key="{{ lookup('file', '/home/user_name/.ssh/id_rsa.pub') }}" 
                    state=present
